package com.huawei.hwcloudmodel.p060b;

import java.util.HashMap;

/* compiled from: InChinaAccount */
final class C4675b extends HashMap<Integer, Integer> {
    C4675b() {
        put(Integer.valueOf(1), Integer.valueOf(1));
        put(Integer.valueOf(2), Integer.valueOf(1));
        put(Integer.valueOf(3), Integer.valueOf(1));
        put(Integer.valueOf(4), Integer.valueOf(1));
        put(Integer.valueOf(5), Integer.valueOf(1));
        put(Integer.valueOf(6), Integer.valueOf(1));
        put(Integer.valueOf(7), Integer.valueOf(1));
        put(Integer.valueOf(8), Integer.valueOf(1));
        put(Integer.valueOf(9), Integer.valueOf(1));
        put(Integer.valueOf(10), Integer.valueOf(1));
        put(Integer.valueOf(11), Integer.valueOf(1));
        put(Integer.valueOf(12), Integer.valueOf(1));
        put(Integer.valueOf(13), Integer.valueOf(1));
        put(Integer.valueOf(14), Integer.valueOf(1));
        put(Integer.valueOf(15), Integer.valueOf(1));
        put(Integer.valueOf(16), Integer.valueOf(1));
        put(Integer.valueOf(17), Integer.valueOf(1));
        put(Integer.valueOf(18), Integer.valueOf(1));
        put(Integer.valueOf(19), Integer.valueOf(1));
        put(Integer.valueOf(20), Integer.valueOf(0));
        put(Integer.valueOf(21), Integer.valueOf(1));
        put(Integer.valueOf(22), Integer.valueOf(1));
        put(Integer.valueOf(23), Integer.valueOf(1));
        put(Integer.valueOf(24), Integer.valueOf(1));
        put(Integer.valueOf(25), Integer.valueOf(1));
        put(Integer.valueOf(26), Integer.valueOf(1));
        put(Integer.valueOf(27), Integer.valueOf(0));
        put(Integer.valueOf(28), Integer.valueOf(1));
        put(Integer.valueOf(29), Integer.valueOf(1));
        put(Integer.valueOf(30), Integer.valueOf(1));
        put(Integer.valueOf(31), Integer.valueOf(1));
        put(Integer.valueOf(32), Integer.valueOf(1));
        put(Integer.valueOf(33), Integer.valueOf(1));
        put(Integer.valueOf(34), Integer.valueOf(1));
        put(Integer.valueOf(35), Integer.valueOf(1));
        put(Integer.valueOf(36), Integer.valueOf(1));
        put(Integer.valueOf(37), Integer.valueOf(1));
        put(Integer.valueOf(38), Integer.valueOf(1));
        put(Integer.valueOf(39), Integer.valueOf(1));
        put(Integer.valueOf(40), Integer.valueOf(1));
        put(Integer.valueOf(41), Integer.valueOf(1));
        put(Integer.valueOf(42), Integer.valueOf(1));
        put(Integer.valueOf(43), Integer.valueOf(1));
        put(Integer.valueOf(44), Integer.valueOf(1));
        put(Integer.valueOf(45), Integer.valueOf(1));
        put(Integer.valueOf(46), Integer.valueOf(1));
        put(Integer.valueOf(47), Integer.valueOf(1));
        put(Integer.valueOf(48), Integer.valueOf(1));
        put(Integer.valueOf(49), Integer.valueOf(0));
        put(Integer.valueOf(50), Integer.valueOf(1));
        put(Integer.valueOf(51), Integer.valueOf(1));
        put(Integer.valueOf(52), Integer.valueOf(1));
        put(Integer.valueOf(53), Integer.valueOf(1));
        put(Integer.valueOf(54), Integer.valueOf(1));
        put(Integer.valueOf(55), Integer.valueOf(1));
        put(Integer.valueOf(56), Integer.valueOf(1));
        put(Integer.valueOf(57), Integer.valueOf(1));
        put(Integer.valueOf(58), Integer.valueOf(1));
        put(Integer.valueOf(59), Integer.valueOf(1));
        put(Integer.valueOf(60), Integer.valueOf(1));
        put(Integer.valueOf(61), Integer.valueOf(1));
    }
}
