package com.google.android.gms.internal;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import com.google.android.gms.common.api.C0366w;
import com.google.android.gms.common.api.C0382t;
import com.google.android.gms.common.api.C0383u;
import com.google.android.gms.common.api.C0385x;
import com.google.android.gms.common.api.Status;
import java.util.concurrent.TimeUnit;

public class bx<R extends C0366w> extends C0382t<R> {
    private final Status f634a;

    @NonNull
    public R mo1846a(long j, @NonNull TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Nullable
    public Integer mo1847a() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public void mo1848a(@NonNull C0383u c0383u) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public void mo1849a(@NonNull C0385x<? super R> c0385x) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @NonNull
    Status m1120b() {
        return this.f634a;
    }
}
